### ISSUE TITLE
Online Hosting

### ISSUE THREAD

**Issue by asayee0** [jefroy/wp-anime-review#10]
[Remote Domain](http://asay.sgedu.site/) for the site.

1. Login credentials: See group conversation.
2. cPanel credentials: See group conversation.
3. Siteground credentials: See group conversaiton.

**Comment by shottah** [comment]
**Workflow**
Any changes made to the code, for example:
1. Custom post definition modifications
2. User role definition motifications
3. Mu-plugin modifications
4. Single post page visual modifications.
5. Archive post page visual modifications.
Should be made locally on a new "feature" branch with a pull request for review as usual. These changes once reviewed will be merged into the master branch.

Any changes made to the database however:
1. Adding custom post content.
2. Adding custom fields and relationships to custom post content.
3. Adding comments to posts and custom posts.
4. Other (?)
Should be made *ONLY* on the staging version of the website located on the remote domain. Optionally, you can migrate the staging domain down to your local installation in order to view content while you design.

**DO NOT MIGRATE THE DATABASE FROM LOCAL TO STAGING OR PRODUCTION**
